name: Store Alerts
 
on:
  schedule:
    - cron: '37 13 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:
 
jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions: 
        contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
        
    - name: Install dependencies
      run: pip install requests
           python -m pip install --upgrade pip
           pip install pandas
      
    - name: Run Python script
      env: 
        TOKEN: ${{secrets.APP_SEC_TOKEN}}
      run: python DataConversion.py

    - name: Commit and push JSON file
      run: |
          git config --global user.name 'sowjanya467'
          git config --global user.email 'msowjanya2014.gmail.com'
          git add code_scanning_alerts.csv
          git commit -m 'Add generated code_scanning_alerts.csv'
          git push
      env:
          TOKEN: ${{ secrets.APP_SEC_TOKEN }}
          
