name: Python Script Scheduler
 
on:
  schedule:
    - cron: '37 13 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:
 
jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
        
    - name: Install dependencies
      run: pip install requests 
      
    - name: Run Python script
      run: python SASTScanning.py

    - name: Upload Results to Artifact
      uses: actions/upload-artifact@v2
      with:
          name: code_scanning_alerts
          path: code_scanning_alerts.json
